// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseUnavailableReason } from './availability';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const isBrowser = typeof window !== "undefined";
const authAvailableAtStartup = !isBrowser || !getSupabaseUnavailableReason();
const OFFLINE_HINT =
  "Run `supabase start --workdir backend` or point frontend/.env.local at your cloud project.";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const getRequestUrl = (input: RequestInfo | URL) => {
  if (typeof input === "string") {
    return input;
  }

  if (input instanceof URL) {
    return input.toString();
  }

  return input.url;
};

const getRequestMethod = (input: RequestInfo | URL, init?: RequestInit) => {
  if (init?.method) {
    return init.method.toUpperCase();
  }

  if (typeof Request !== "undefined" && input instanceof Request) {
    return input.method.toUpperCase();
  }

  return "GET";
};

const jsonResponse = (body: unknown, init: ResponseInit) =>
  new Response(JSON.stringify(body), {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...(init.headers ?? {}),
    },
  });

const buildOfflineResponse = (input: RequestInfo | URL, init?: RequestInit) => {
  const reason = getSupabaseUnavailableReason();

  if (!reason) {
    return null;
  }

  const url = getRequestUrl(input);
  const method = getRequestMethod(input, init);

  if (url.includes("/auth/v1/")) {
    return jsonResponse(
      {
        msg: reason,
        error: reason,
        error_description: reason,
      },
      { status: 400, statusText: "Bad Request" },
    );
  }

  if (url.includes("/functions/v1/search-books")) {
    return jsonResponse({ results: [] }, { status: 200, statusText: "OK" });
  }

  if (url.includes("/rest/v1/rpc/search_books_fuzzy")) {
    return jsonResponse([], { status: 200, statusText: "OK" });
  }

  if (url.includes("/rest/v1/") && method === "HEAD") {
    return new Response(null, {
      status: 200,
      statusText: "OK",
      headers: {
        "Content-Range": "0-0/0",
      },
    });
  }

  if (url.includes("/rest/v1/") && method === "GET") {
    return jsonResponse([], {
      status: 200,
      statusText: "OK",
      headers: {
        "Content-Range": "0-0/0",
      },
    });
  }

  return jsonResponse(
    {
      code: "local_supabase_unavailable",
      details: reason,
      hint: OFFLINE_HINT,
      message: reason,
    },
    { status: 400, statusText: "Bad Request" },
  );
};

const supabaseFetch: typeof fetch = async (input, init) => {
  const offlineResponse = buildOfflineResponse(input, init);

  if (offlineResponse) {
    return offlineResponse;
  }

  return fetch(input, init);
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: supabaseFetch,
  },
  auth: {
    storage: isBrowser && authAvailableAtStartup ? window.localStorage : undefined,
    persistSession: isBrowser && authAvailableAtStartup,
    autoRefreshToken: isBrowser && authAvailableAtStartup,
    detectSessionInUrl: false,
    flowType: "pkce",
  },
});
