// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import {
  CLOUD_SUPABASE_UNAVAILABLE_MESSAGE,
  getDefaultSupabaseUnavailableMessage,
  getSupabaseUnavailableReason,
  isLoopbackSupabaseUrl,
  LOCAL_SUPABASE_UNAVAILABLE_MESSAGE,
  markSupabaseUnavailable,
} from './availability';
import {
  hasSupabaseConfig,
  isLoopbackHostname,
  SUPABASE_PUBLISHABLE_KEY,
  SUPABASE_URL,
} from "./config";

const FALLBACK_SUPABASE_URL = "https://placeholder.supabase.co";
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = "public-anon-key-placeholder";
const LOCAL_DEV_SUPABASE_URL = "http://127.0.0.1:54321";
const LOCAL_DEV_SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";
const isBrowser = typeof window !== "undefined";

const isPrivateNetworkHostname = (hostname: string) => {
  if (isLoopbackHostname(hostname)) {
    return true;
  }

  if (/^192\.168\.\d{1,3}\.\d{1,3}$/.test(hostname) || /^10\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(hostname)) {
    return true;
  }

  const match = hostname.match(/^172\.(\d{1,2})\.\d{1,3}\.\d{1,3}$/);
  return Boolean(match && Number(match[1]) >= 16 && Number(match[1]) <= 31);
};

const isLocalDevelopmentBrowser = isBrowser && isPrivateNetworkHostname(window.location.hostname);
const shouldForceLocalSupabase = isLocalDevelopmentBrowser && !isLoopbackSupabaseUrl;
const resolvedSupabaseUrl = shouldForceLocalSupabase
  ? LOCAL_DEV_SUPABASE_URL
  : hasSupabaseConfig
    ? SUPABASE_URL
    : FALLBACK_SUPABASE_URL;
const resolvedSupabaseKey = shouldForceLocalSupabase
  ? LOCAL_DEV_SUPABASE_ANON_KEY
  : hasSupabaseConfig
    ? SUPABASE_PUBLISHABLE_KEY
    : FALLBACK_SUPABASE_PUBLISHABLE_KEY;
const authAvailableAtStartup = !isBrowser || !getSupabaseUnavailableReason();
const OFFLINE_HINT =
  "Run `supabase start --workdir backend` or point frontend/.env.local at your cloud project.";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const getRequestUrl = (input: RequestInfo | URL) => {
  if (typeof input === "string") {
    return input;
  }

  if (input instanceof URL) {
    return input.toString();
  }

  return input.url;
};

const getRequestMethod = (input: RequestInfo | URL, init?: RequestInit) => {
  if (init?.method) {
    return init.method.toUpperCase();
  }

  if (typeof Request !== "undefined" && input instanceof Request) {
    return input.method.toUpperCase();
  }

  return "GET";
};

const getRequestHostname = (input: RequestInfo | URL) => {
  try {
    return new URL(getRequestUrl(input)).hostname;
  } catch {
    return null;
  }
};

const jsonResponse = (body: unknown, init: ResponseInit) =>
  new Response(JSON.stringify(body), {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...(init.headers ?? {}),
    },
  });

const buildOfflineResponse = (input: RequestInfo | URL, init?: RequestInit) => {
  const reason = getSupabaseUnavailableReason();

  if (!reason) {
    return null;
  }

  const url = getRequestUrl(input);
  const method = getRequestMethod(input, init);

  if (url.includes("/auth/v1/")) {
    return jsonResponse(
      {
        msg: reason,
        error: reason,
        error_description: reason,
      },
      { status: 400, statusText: "Bad Request" },
    );
  }

  if (url.includes("/functions/v1/search-books")) {
    return jsonResponse({ results: [] }, { status: 200, statusText: "OK" });
  }

  if (url.includes("/rest/v1/rpc/search_books_fuzzy")) {
    return jsonResponse([], { status: 200, statusText: "OK" });
  }

  if (url.includes("/rest/v1/") && method === "HEAD") {
    return new Response(null, {
      status: 200,
      statusText: "OK",
      headers: {
        "Content-Range": "0-0/0",
      },
    });
  }

  if (url.includes("/rest/v1/") && method === "GET") {
    return jsonResponse([], {
      status: 200,
      statusText: "OK",
      headers: {
        "Content-Range": "0-0/0",
      },
    });
  }

  return jsonResponse(
    {
      code: "local_supabase_unavailable",
      details: reason,
      hint: OFFLINE_HINT,
      message: reason,
    },
    { status: 400, statusText: "Bad Request" },
  );
};

const buildAuthNetworkErrorResponse = (message: string, status = 503) =>
  jsonResponse(
    {
      msg: message,
      error: message,
      error_description: message,
    },
    {
      status,
      statusText: status === 503 ? "Service Unavailable" : "Bad Request",
    },
  );

const supabaseFetch: typeof fetch = async (input, init) => {
  const offlineResponse = buildOfflineResponse(input, init);

  if (offlineResponse) {
    return offlineResponse;
  }

  try {
    return await fetch(input, init);
  } catch (error) {
    const url = getRequestUrl(input);

    if (!url.includes("/auth/v1/")) {
      throw error;
    }

    const hostname = getRequestHostname(input);
    const loopbackFailure =
      isLoopbackSupabaseUrl || hostname === "127.0.0.1" || hostname === "localhost" || hostname === "::1";
    const reason = loopbackFailure
      ? LOCAL_SUPABASE_UNAVAILABLE_MESSAGE
      : getSupabaseUnavailableReason() ?? getDefaultSupabaseUnavailableMessage() ?? CLOUD_SUPABASE_UNAVAILABLE_MESSAGE;

    markSupabaseUnavailable(reason);

    if (loopbackFailure) {
      return buildOfflineResponse(input, init) ?? buildAuthNetworkErrorResponse(reason, 400);
    }

    return buildOfflineResponse(input, init) ?? buildAuthNetworkErrorResponse(reason, 503);
  }
};

export const supabase = createClient<Database>(
  resolvedSupabaseUrl,
  resolvedSupabaseKey,
  {
    global: {
      fetch: supabaseFetch,
    },
    auth: {
      storage: isBrowser && authAvailableAtStartup ? window.localStorage : undefined,
      persistSession: isBrowser && authAvailableAtStartup,
      autoRefreshToken: isBrowser && authAvailableAtStartup,
      detectSessionInUrl: false,
      flowType: "pkce",
    },
  },
);
