import type { Book } from "@/types/library";

type FallbackBookSeed = {
  id: string;
  title: string;
  author: string;
  genre: string;
  description: string;
  language?: string;
  total_copies?: number;
  available_copies?: number;
  borrow_price?: number;
  borrow_currency?: string;
  is_public_readable?: boolean;
  reading_content?: string[] | null;
};

const createFallbackBook = ({
  language = "en",
  total_copies = 4,
  available_copies = total_copies,
  is_public_readable = false,
  borrow_price = is_public_readable ? 0 : 3500,
  borrow_currency = "MNT",
  reading_content = null,
  ...book
}: FallbackBookSeed): Book => ({
  ...book,
  language,
  cover_url: null,
  total_copies,
  available_copies,
  borrow_price,
  borrow_currency,
  is_public_readable,
  reading_content,
});

const extendedFallbackBooks: FallbackBookSeed[] = [
  {
    id: "fallback-the-glass-harbor",
    title: "The Glass Harbor",
    author: "Mirelle Dastan",
    genre: "Literature",
    description: "A luminous novel of exile, return, and the fragile architectures people call home.",
    total_copies: 6,
  },
  {
    id: "fallback-winter-letters-to-odessa",
    title: "Winter Letters to Odessa",
    author: "Nikolai Serov",
    genre: "Literature",
    description: "Epistolary fiction about memory, ports, and the way distance edits love.",
    total_copies: 4,
    available_copies: 3,
  },
  {
    id: "fallback-last-lantern-street",
    title: "The Last Lantern Street",
    author: "Amara Finch",
    genre: "Literature",
    description: "A city novel following four intertwined lives through blackout nights and quiet revolutions.",
    total_copies: 5,
  },
  {
    id: "fallback-sand-atlas-for-the-homesick",
    title: "Sand Atlas for the Homesick",
    author: "Rahim Soltan",
    genre: "Literature",
    description: "A lyrical journey across deserts and memory for readers who collect places they can no longer inhabit.",
    total_copies: 5,
    is_public_readable: true,
  },
  {
    id: "fallback-saltwind-psalms",
    title: "Saltwind Psalms",
    author: "Eva Maren",
    genre: "Poetry",
    description: "Sea-lit poems on tenderness, migration, and the devotional language of weather.",
    total_copies: 4,
    is_public_readable: true,
  },
  {
    id: "fallback-night-orchard-sonnets",
    title: "Night Orchard Sonnets",
    author: "T. Rowan",
    genre: "Poetry",
    description: "A formally precise collection rooted in grief, fruit trees, and inherited silence.",
    total_copies: 3,
  },
  {
    id: "fallback-blue-fire-haiku",
    title: "Blue Fire Haiku",
    author: "Sumi Arai",
    genre: "Poetry",
    description: "Small, clean poems attentive to sky, ash, breath, and transient forms of wonder.",
    total_copies: 5,
    available_copies: 4,
  },
  {
    id: "fallback-river-of-quiet-names",
    title: "River of Quiet Names",
    author: "Battulga Munkh",
    genre: "Poetry",
    description: "Mongolian and English poems tracing family names, rivers, and vanishing geographies.",
    language: "mn",
    total_copies: 4,
  },
  {
    id: "fallback-architecture-of-habit",
    title: "The Architecture of Habit",
    author: "Dr. Lena Ivers",
    genre: "Psychology",
    description: "A practical and humane guide to routines, identity, and the environments that shape behavior.",
    total_copies: 7,
  },
  {
    id: "fallback-rooms-of-attention",
    title: "Rooms of Attention",
    author: "Miles Kettering",
    genre: "Psychology",
    description: "On focus, distraction, and how attention can be designed rather than merely defended.",
    total_copies: 5,
    available_copies: 4,
  },
  {
    id: "fallback-maps-for-grief",
    title: "Maps for Grief",
    author: "Nadia Feld",
    genre: "Psychology",
    description: "A compassionate synthesis of mourning research, ritual practice, and lived testimony.",
    total_copies: 4,
    is_public_readable: true,
  },
  {
    id: "fallback-social-brain-notebook",
    title: "The Social Brain Notebook",
    author: "Hugo Park",
    genre: "Psychology",
    description: "A readable introduction to attachment, perception, and the hidden negotiations of everyday relationships.",
    total_copies: 6,
  },
  {
    id: "fallback-markets-after-midnight",
    title: "Markets After Midnight",
    author: "Clara Mendes",
    genre: "Economics",
    description: "An accessible account of informal trade, night economies, and the human texture behind price signals.",
    total_copies: 5,
  },
  {
    id: "fallback-price-of-distance",
    title: "The Price of Distance",
    author: "Jonah Bale",
    genre: "Economics",
    description: "How transport, remoteness, and infrastructure quietly decide who gets included in prosperity.",
    total_copies: 5,
  },
  {
    id: "fallback-port-cities-paper-money",
    title: "Port Cities and Paper Money",
    author: "Elena Rossi",
    genre: "Economics",
    description: "A historical economics study of ports, credit, and the institutions that turn movement into value.",
    total_copies: 4,
    available_copies: 3,
  },
  {
    id: "fallback-commons-small-republic",
    title: "Commons of the Small Republic",
    author: "Ilyas Noor",
    genre: "Economics",
    description: "A civic-minded argument for shared systems, local stewardship, and resilient public life.",
    total_copies: 4,
  },
  {
    id: "fallback-quiet-systems",
    title: "Quiet Systems",
    author: "Marta Belen",
    genre: "Design",
    description: "Designing products and spaces that remove friction without demanding constant attention.",
    total_copies: 5,
  },
  {
    id: "fallback-type-and-tension",
    title: "Type and Tension",
    author: "Oren Vale",
    genre: "Design",
    description: "A typography book about rhythm, contrast, legibility, and the drama of restraint.",
    total_copies: 4,
  },
  {
    id: "fallback-everyday-interfaces",
    title: "Everyday Interfaces",
    author: "Celine Ho",
    genre: "Design",
    description: "On interface patterns, humane defaults, and designing for clarity rather than noise.",
    total_copies: 6,
    is_public_readable: true,
  },
  {
    id: "fallback-objects-that-listen",
    title: "Objects That Listen",
    author: "Kian Mercer",
    genre: "Design",
    description: "A study of tactile design, affordance, and why the best objects feel cooperative.",
    total_copies: 4,
  },
  {
    id: "fallback-moss-cartographies",
    title: "Moss Cartographies",
    author: "Rina Thorsen",
    genre: "Ecology",
    description: "Tiny landscapes, moss ecologies, and what small systems teach about resilience.",
    total_copies: 4,
    is_public_readable: true,
  },
  {
    id: "fallback-rivers-that-remember",
    title: "Rivers That Remember",
    author: "Daniel Quen",
    genre: "Ecology",
    description: "A river-centered account of restoration, watershed politics, and ecological memory.",
    total_copies: 5,
  },
  {
    id: "fallback-forest-second-language",
    title: "The Forest's Second Language",
    author: "Alina Brook",
    genre: "Ecology",
    description: "Field essays on canopy intelligence, soil networks, and the ethics of observation.",
    total_copies: 6,
  },
  {
    id: "fallback-weather-ethics",
    title: "Weather Ethics",
    author: "B. Tserendolgor",
    genre: "Ecology",
    description: "Climate writing that links policy, grief, and everyday accountability without surrendering hope.",
    language: "mn",
    total_copies: 4,
  },
  {
    id: "fallback-grammar-of-wandering-tongues",
    title: "Grammar of Wandering Tongues",
    author: "Professor Lea Harun",
    genre: "Linguistics",
    description: "On migration, multilingual identity, and how grammar travels with communities.",
    total_copies: 5,
  },
  {
    id: "fallback-syntax-of-silence",
    title: "Syntax of Silence",
    author: "Mateo Sire",
    genre: "Linguistics",
    description: "A reflective study of pause, omission, and what speech leaves unsaid.",
    total_copies: 4,
  },
  {
    id: "fallback-borrowed-alphabets",
    title: "Borrowed Alphabets",
    author: "Yuna Sharipova",
    genre: "Linguistics",
    description: "Scripts, transliteration, and the politics of writing across borders.",
    total_copies: 6,
    available_copies: 5,
  },
  {
    id: "fallback-names-across-borders",
    title: "Names Across Borders",
    author: "Ganbold Erkh",
    genre: "Linguistics",
    description: "Personal names as records of migration, kinship, aspiration, and translation.",
    language: "mn",
    total_copies: 3,
  },
  {
    id: "fallback-proofs-at-dawn",
    title: "Proofs at Dawn",
    author: "Helene Morot",
    genre: "Mathematics",
    description: "A warm introduction to proof, elegance, and the emotional life of mathematical thought.",
    total_copies: 5,
  },
  {
    id: "fallback-infinity-in-small-rooms",
    title: "Infinity in Small Rooms",
    author: "Rafael Dane",
    genre: "Mathematics",
    description: "Big ideas in infinity and abstraction told through intimate, human-scale examples.",
    total_copies: 4,
  },
  {
    id: "fallback-geometry-of-wind",
    title: "The Geometry of Wind",
    author: "S. Naranbaatar",
    genre: "Mathematics",
    description: "Patterns, curves, and symmetries discovered in dunes, storms, and moving air.",
    total_copies: 4,
    is_public_readable: true,
  },
  {
    id: "fallback-number-fields-human-beings",
    title: "Number Fields for Human Beings",
    author: "Clive Redfern",
    genre: "Mathematics",
    description: "A bridge between abstract algebra and intuitive storytelling for persistent readers.",
    total_copies: 3,
  },
  {
    id: "fallback-ada-engines-of-imagination",
    title: "Ada and the Engines of Imagination",
    author: "Marina Holt",
    genre: "Biography",
    description: "A literary biography of Ada Lovelace focused on pattern, metaphor, and invention.",
    total_copies: 5,
  },
  {
    id: "fallback-tserendorj-restless-century",
    title: "Tserendorj: Notes from a Restless Century",
    author: "Oyungerel Bat",
    genre: "Biography",
    description: "A layered portrait of a twentieth-century Mongolian intellectual navigating upheaval and duty.",
    language: "mn",
    total_copies: 4,
  },
  {
    id: "fallback-curie-in-winter",
    title: "Curie in Winter",
    author: "Elise Fournier",
    genre: "Biography",
    description: "Science, exhaustion, persistence, and the private winters that shape public brilliance.",
    total_copies: 4,
  },
  {
    id: "fallback-cartographers-daughter",
    title: "The Cartographer's Daughter",
    author: "Hanna Velas",
    genre: "Biography",
    description: "The life of a mapmaker told through family archives, expedition diaries, and unfinished sketches.",
    total_copies: 3,
  },
  {
    id: "fallback-stone-light-and-silence",
    title: "Stone, Light, and Silence",
    author: "Rami El-Khatib",
    genre: "Architecture",
    description: "How light, material, and emptiness shape spaces people remember long after leaving them.",
    total_copies: 5,
  },
  {
    id: "fallback-cities-for-slow-feet",
    title: "Cities for Slow Feet",
    author: "Nina Verhoeven",
    genre: "Architecture",
    description: "Urban design for walking, lingering, conversation, and public dignity.",
    total_copies: 6,
  },
  {
    id: "fallback-courtyard-futures",
    title: "Courtyard Futures",
    author: "Tserenjav Bold",
    genre: "Architecture",
    description: "Traditional spatial wisdom reimagined for dense contemporary neighborhoods.",
    language: "mn",
    total_copies: 4,
  },
  {
    id: "fallback-timber-and-dust",
    title: "Timber and Dust",
    author: "Ava Lin",
    genre: "Architecture",
    description: "A material history of wood, earth, and repair-minded building traditions.",
    total_copies: 4,
  },
  {
    id: "fallback-protocols-for-kind-machines",
    title: "Protocols for Kind Machines",
    author: "Isabel Kerr",
    genre: "Technology",
    description: "What humane systems design could look like when care becomes a technical requirement.",
    total_copies: 5,
  },
  {
    id: "fallback-cloud-and-the-workshop",
    title: "The Cloud and the Workshop",
    author: "Devin Chuluun",
    genre: "Technology",
    description: "A grounded exploration of cloud tools, craft knowledge, and the future of digital work.",
    total_copies: 5,
  },
  {
    id: "fallback-hardware-for-fragile-worlds",
    title: "Hardware for Fragile Worlds",
    author: "Aya Morgan",
    genre: "Technology",
    description: "Designing robust systems for unstable environments, limited power, and imperfect networks.",
    total_copies: 4,
  },
  {
    id: "fallback-after-the-interface",
    title: "After the Interface",
    author: "Pavel Noorov",
    genre: "Technology",
    description: "A cultural history of screens, interaction, and what comes after familiar interface metaphors.",
    total_copies: 4,
    available_copies: 3,
  },
  {
    id: "fallback-pilgrim-of-the-inner-sky",
    title: "Pilgrim of the Inner Sky",
    author: "Sister Elowen",
    genre: "Spirituality",
    description: "A contemplative guide to attention, surrender, and disciplined wonder.",
    total_copies: 4,
    is_public_readable: true,
  },
  {
    id: "fallback-monasteries-of-breath",
    title: "Monasteries of Breath",
    author: "Tashi Lhamo",
    genre: "Spirituality",
    description: "On breath practice, repetition, and the hidden architecture of interior stillness.",
    total_copies: 4,
  },
  {
    id: "fallback-desert-bells-at-noon",
    title: "Desert Bells at Noon",
    author: "Hamed Safi",
    genre: "Spirituality",
    description: "A luminous sequence of essays on solitude, prayer, and moral clarity under harsh light.",
    total_copies: 3,
  },
  {
    id: "fallback-prayer-and-attention",
    title: "Prayer and Attention",
    author: "Anuujin Dorj",
    genre: "Spirituality",
    description: "A cross-tradition study of reverence, focus, and the ethics of returning to practice.",
    language: "mn",
    total_copies: 4,
  },
];

const publicDomainShelfBooks: FallbackBookSeed[] = [
  {
    id: "fallback-pride-and-prejudice",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Classics",
    description:
      "A sharp, witty classic about first impressions, family pressures, and a love that learns to deserve itself.",
    total_copies: 12,
    available_copies: 12,
    reading_content: [
      "It is a truth universally acknowledged, that a single man in possession of a good fortune must be in want of a wife.",
      "However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered as the rightful property of some one or other of their daughters.",
      "\"My dear Mr. Bennet,\" said his lady to him one day, \"have you heard that Netherfield Park is let at last?\"",
      "\"But it is,\" returned she; \"for Mrs. Long has just been here, and she told me all about it.\"",
      "\"Why, my dear, you must know, Mrs. Long says that Netherfield is taken by a young man of large fortune from the north of England; that he came down on Monday in a chaise and four to see the place, and was so much delighted with it that he agreed with Mr. Morris immediately; that he is to take possession before Michaelmas, and some of his servants are to be in the house by the end of next week.\"",
      "\"Oh, single, my dear, to be sure! A single man of large fortune; four or five thousand a year. What a fine thing for our girls!\"",
      "\"My dear Mr. Bennet,\" replied his wife, \"how can you be so tiresome? You must know that I am thinking of his marrying one of them.\"",
      "\"Design? Nonsense, how can you talk so! But it is very likely that he may fall in love with one of them, and therefore you must visit him as soon as he comes.\"",
      "\"I see no occasion for that. You and the girls may go -- or you may send them by themselves, which perhaps will be still better; for as you are as handsome as any of them, Mr. Bingley might like you the best of the party.\"",
    ],
  },
  {
    id: "fallback-frankenstein",
    title: "Frankenstein",
    author: "Mary Shelley",
    genre: "Classics",
    description:
      "A foundational Gothic novel about ambition, responsibility, and the loneliness created when invention outruns compassion.",
    total_copies: 10,
    available_copies: 10,
    reading_content: [
      "You will rejoice to hear that no disaster has accompanied the commencement of an enterprise which you have regarded with such evil forebodings.",
      "I arrived here yesterday, and my first task is to assure my dear sister of my welfare and increasing confidence in the success of my undertaking.",
      "I am already far north of London, and as I walk in the streets of Petersburgh, I feel a cold northern breeze play upon my cheeks, which braces my nerves and fills me with delight.",
      "Do you understand this feeling? This breeze, which has travelled from the regions towards which I am advancing, gives me a foretaste of those icy climes.",
    ],
  },
  {
    id: "fallback-the-secret-garden",
    title: "The Secret Garden",
    author: "Frances Hodgson Burnett",
    genre: "Classics",
    description:
      "A restorative classic in which grief, friendship, and a neglected garden slowly bring a household back to life.",
    total_copies: 9,
    available_copies: 9,
    reading_content: [
      "When Mary Lennox was sent to Misselthwaite Manor to live with her uncle everybody said she was the most disagreeable-looking child ever seen.",
      "It was true, too. She had a little thin face and a little thin body, thin light hair and a sour expression.",
      "Her hair was yellow, and her face was yellow because she had been born in India and had always been ill in one way or another.",
      "Her father had held a position under the English Government and had always been busy and ill himself, and her mother had been a great beauty who cared only to go to parties and amuse herself with gay people.",
    ],
  },
  {
    id: "fallback-adventures-of-sherlock-holmes",
    title: "The Adventures of Sherlock Holmes",
    author: "Arthur Conan Doyle",
    genre: "Mystery",
    description:
      "Twelve detective adventures filled with deduction, disguises, and the brisk intelligence of Baker Street.",
    total_copies: 11,
    available_copies: 11,
    reading_content: [
      "To Sherlock Holmes she is always the woman. I have seldom heard him mention her under any other name.",
      "In his eyes she eclipses and predominates the whole of her sex. It was not that he felt any emotion akin to love for Irene Adler.",
      "All emotions, and that one particularly, were abhorrent to his cold, precise but admirably balanced mind.",
      "He was, I take it, the most perfect reasoning and observing machine that the world has seen, but as a lover he would have placed himself in a false position.",
    ],
  },
  {
    id: "fallback-the-wonderful-wizard-of-oz",
    title: "The Wonderful Wizard of Oz",
    author: "L. Frank Baum",
    genre: "Fantasy",
    description:
      "A bright American fantasy about courage, tenderness, and the strange companions found on the road home.",
    total_copies: 8,
    available_copies: 8,
    reading_content: [
      "Dorothy lived in the midst of the great Kansas prairies, with Uncle Henry, who was a farmer, and Aunt Em, who was the farmer's wife.",
      "Their house was small, for the lumber to build it had to be carried by wagon many miles.",
      "There were four walls, a floor and a roof, which made one room; and this room contained a rusty looking cookstove, a cupboard for the dishes, a table, three or four chairs, and the beds.",
      "When Aunt Em came there to live she was a young, pretty wife. The sun and wind had changed her, too.",
    ],
  },
  {
    id: "fallback-a-little-princess",
    title: "A Little Princess",
    author: "Frances Hodgson Burnett",
    genre: "Classics",
    description:
      "A resilient coming-of-age classic about imagination, dignity, and kindness preserved under hardship.",
    total_copies: 8,
    available_copies: 7,
    reading_content: [
      "Once on a dark winter's day, when the yellow fog hung so thick and heavy in the streets of London that the lamps were lighted and the shop fronts looked as if they were already beginning to prepare for night, there drove up to the door of Miss Minchin's Select Seminary for Young Ladies a rather dingy cab.",
      "It was the arrival of a new pupil who had left India with her papa to be placed at school.",
      "As the big cab drew up, Miss Minchin, who was watching it from the front drawing-room, came out to meet the little girl when she was brought into the house by her father.",
      "Sara Crewe was seven years old. She was a queer little figure, dressed in deep mourning, and holding herself very erect.",
    ],
  },
  {
    id: "fallback-sense-and-sensibility",
    title: "Sense and Sensibility",
    author: "Jane Austen",
    genre: "Classics",
    description:
      "Austen's elegant study of sisters, feeling, restraint, and the social pressure surrounding love and money.",
    total_copies: 10,
    available_copies: 10,
    is_public_readable: true,
  },
  {
    id: "fallback-emma",
    title: "Emma",
    author: "Jane Austen",
    genre: "Classics",
    description:
      "A witty comedy of misread intentions, class confidence, and the slow education of a clever heroine.",
    total_copies: 10,
    available_copies: 10,
    is_public_readable: true,
  },
  {
    id: "fallback-persuasion",
    title: "Persuasion",
    author: "Jane Austen",
    genre: "Classics",
    description:
      "A quiet, mature romance about regret, second chances, and the courage to trust an old feeling again.",
    total_copies: 9,
    available_copies: 9,
    is_public_readable: true,
  },
  {
    id: "fallback-great-expectations",
    title: "Great Expectations",
    author: "Charles Dickens",
    genre: "Classics",
    description:
      "Dickens follows ambition, shame, money, and loyalty through one of fiction's great coming-of-age arcs.",
    total_copies: 12,
    available_copies: 12,
    is_public_readable: true,
  },
  {
    id: "fallback-a-tale-of-two-cities",
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    genre: "Historical Fiction",
    description:
      "A revolutionary-era novel of sacrifice, terror, memory, and private devotion under public violence.",
    total_copies: 12,
    available_copies: 12,
    is_public_readable: true,
  },
  {
    id: "fallback-oliver-twist",
    title: "Oliver Twist",
    author: "Charles Dickens",
    genre: "Classics",
    description:
      "A social novel about childhood vulnerability, criminal networks, and the hunger for safety and belonging.",
    total_copies: 10,
    available_copies: 10,
    is_public_readable: true,
  },
  {
    id: "fallback-wuthering-heights",
    title: "Wuthering Heights",
    author: "Emily Bronte",
    genre: "Gothic",
    description:
      "A fierce Gothic novel of obsession, inheritance, landscape, and love that refuses to become gentle.",
    total_copies: 10,
    available_copies: 10,
    is_public_readable: true,
  },
  {
    id: "fallback-little-women",
    title: "Little Women",
    author: "Louisa May Alcott",
    genre: "Classics",
    description:
      "A beloved family novel about sisters, work, art, moral growth, and the intimate heroism of ordinary life.",
    total_copies: 11,
    available_copies: 11,
    is_public_readable: true,
  },
  {
    id: "fallback-anne-of-green-gables",
    title: "Anne of Green Gables",
    author: "L. M. Montgomery",
    genre: "Children's Literature",
    description:
      "A radiant coming-of-age story about imagination, belonging, friendship, and the making of a home.",
    total_copies: 10,
    available_copies: 10,
    is_public_readable: true,
  },
  {
    id: "fallback-the-wind-in-the-willows",
    title: "The Wind in the Willows",
    author: "Kenneth Grahame",
    genre: "Children's Literature",
    description:
      "A riverbank classic of friendship, restlessness, hospitality, and the gentle comedy of creaturely life.",
    total_copies: 8,
    available_copies: 8,
    is_public_readable: true,
  },
  {
    id: "fallback-peter-pan",
    title: "Peter Pan",
    author: "J. M. Barrie",
    genre: "Fantasy",
    description:
      "A dreamlike fantasy about childhood, danger, play, and the ache hidden inside never growing up.",
    total_copies: 9,
    available_copies: 9,
    is_public_readable: true,
  },
  {
    id: "fallback-the-call-of-the-wild",
    title: "The Call of the Wild",
    author: "Jack London",
    genre: "Adventure",
    description:
      "A lean adventure of instinct, survival, violence, and the pull of an older wilderness.",
    total_copies: 8,
    available_copies: 8,
    is_public_readable: true,
  },
  {
    id: "fallback-white-fang",
    title: "White Fang",
    author: "Jack London",
    genre: "Adventure",
    description:
      "London reverses the wilderness journey in a story about fear, discipline, trust, and domestication.",
    total_copies: 8,
    available_copies: 8,
    is_public_readable: true,
  },
  {
    id: "fallback-around-the-world-in-eighty-days",
    title: "Around the World in Eighty Days",
    author: "Jules Verne",
    genre: "Adventure",
    description:
      "A brisk global race built from timetables, chance, loyalty, and the pleasures of precise adventure.",
    total_copies: 9,
    available_copies: 9,
    is_public_readable: true,
  },
  {
    id: "fallback-twenty-thousand-leagues-under-the-seas",
    title: "Twenty Thousand Leagues under the Seas",
    author: "Jules Verne",
    genre: "Science Fiction",
    description:
      "A submarine voyage through wonder, science, isolation, and Captain Nemo's wounded mystery.",
    total_copies: 9,
    available_copies: 9,
    is_public_readable: true,
  },
  {
    id: "fallback-flatland",
    title: "Flatland",
    author: "Edwin A. Abbott",
    genre: "Science Fiction",
    description:
      "A mathematical satire that turns geometry into social critique, wonder, and dimensional imagination.",
    total_copies: 7,
    available_copies: 7,
    is_public_readable: true,
  },
  {
    id: "fallback-the-strange-case-of-dr-jekyll-and-mr-hyde",
    title: "The Strange Case of Dr. Jekyll and Mr. Hyde",
    author: "Robert Louis Stevenson",
    genre: "Gothic",
    description:
      "A compact Gothic classic about divided identity, secrecy, reputation, and moral self-deception.",
    total_copies: 9,
    available_copies: 9,
    is_public_readable: true,
  },
  {
    id: "fallback-the-hound-of-the-baskervilles",
    title: "The Hound of the Baskervilles",
    author: "Arthur Conan Doyle",
    genre: "Mystery",
    description:
      "A moody Sherlock Holmes mystery where rational detection moves through legend, fog, and fear.",
    total_copies: 10,
    available_copies: 10,
    is_public_readable: true,
  },
  {
    id: "fallback-the-memoirs-of-sherlock-holmes",
    title: "The Memoirs of Sherlock Holmes",
    author: "Arthur Conan Doyle",
    genre: "Mystery",
    description:
      "A sharp collection of Holmes cases showing disguise, deduction, professional rivalry, and danger.",
    total_copies: 10,
    available_copies: 10,
    is_public_readable: true,
  },
  {
    id: "fallback-the-moonstone",
    title: "The Moonstone",
    author: "Wilkie Collins",
    genre: "Mystery",
    description:
      "A landmark detective novel of testimony, suspicion, imperial loot, and a jewel that unsettles everyone near it.",
    total_copies: 8,
    available_copies: 8,
    is_public_readable: true,
  },
  {
    id: "fallback-the-woman-in-white",
    title: "The Woman in White",
    author: "Wilkie Collins",
    genre: "Mystery",
    description:
      "A sensation novel of identity, conspiracy, inheritance, and testimony assembled with tightening suspense.",
    total_copies: 8,
    available_copies: 8,
    is_public_readable: true,
  },
  {
    id: "fallback-the-turn-of-the-screw",
    title: "The Turn of the Screw",
    author: "Henry James",
    genre: "Gothic",
    description:
      "An ambiguous ghost story about perception, authority, innocence, and the terror of uncertain evidence.",
    total_copies: 7,
    available_copies: 7,
    is_public_readable: true,
  },
  {
    id: "fallback-the-awakening",
    title: "The Awakening",
    author: "Kate Chopin",
    genre: "Fiction",
    description:
      "A spare, intense novel about desire, selfhood, marriage, and the cost of awakening in a narrow world.",
    total_copies: 8,
    available_copies: 8,
    is_public_readable: true,
  },
  {
    id: "fallback-the-yellow-wallpaper",
    title: "The Yellow Wallpaper",
    author: "Charlotte Perkins Gilman",
    genre: "Fiction",
    description:
      "A brief and devastating story about confinement, medical authority, voice, and psychological collapse.",
    total_copies: 7,
    available_copies: 7,
    is_public_readable: true,
  },
  {
    id: "fallback-crime-and-punishment",
    title: "Crime and Punishment",
    author: "Fyodor Dostoyevsky",
    genre: "Classics",
    description:
      "A psychological novel of guilt, poverty, pride, suffering, and the search for moral regeneration.",
    total_copies: 10,
    available_copies: 10,
    is_public_readable: true,
  },
  {
    id: "fallback-war-and-peace",
    title: "War and Peace",
    author: "Leo Tolstoy",
    genre: "Classics",
    description:
      "Tolstoy's vast novel of families, war, history, love, and the limits of individual command.",
    total_copies: 12,
    available_copies: 12,
    is_public_readable: true,
  },
  {
    id: "fallback-anna-karenina",
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    genre: "Classics",
    description:
      "A sweeping novel of marriage, desire, society, agriculture, faith, and the consequences of divided lives.",
    total_copies: 11,
    available_copies: 11,
    is_public_readable: true,
  },
  {
    id: "fallback-the-odyssey",
    title: "The Odyssey",
    author: "Homer",
    genre: "Epic Poetry",
    description:
      "An ancient homecoming epic of cunning, longing, hospitality, violence, and the pull of Ithaca.",
    total_copies: 10,
    available_copies: 10,
    is_public_readable: true,
  },
  {
    id: "fallback-the-art-of-war",
    title: "The Art of War",
    author: "Sun Tzu",
    genre: "Strategy",
    description:
      "A compact strategic classic about perception, timing, discipline, and winning before conflict hardens.",
    total_copies: 9,
    available_copies: 9,
    is_public_readable: true,
  },
  {
    id: "fallback-meditations",
    title: "Meditations",
    author: "Marcus Aurelius",
    genre: "Philosophy",
    description:
      "Private Stoic reflections on attention, mortality, duty, self-command, and meeting the day honestly.",
    total_copies: 9,
    available_copies: 9,
    is_public_readable: true,
  },
  {
    id: "fallback-walden",
    title: "Walden",
    author: "Henry David Thoreau",
    genre: "Nature",
    description:
      "A reflective experiment in simple living, observation, labor, solitude, and the moral pressure of nature.",
    total_copies: 8,
    available_copies: 8,
    is_public_readable: true,
  },
  {
    id: "fallback-the-souls-of-black-folk",
    title: "The Souls of Black Folk",
    author: "W. E. B. Du Bois",
    genre: "History",
    description:
      "A foundational work of history, sociology, music, and political thought on Black life after Reconstruction.",
    total_copies: 8,
    available_copies: 8,
    is_public_readable: true,
  },
  {
    id: "fallback-narrative-of-the-life-of-frederick-douglass",
    title: "Narrative of the Life of Frederick Douglass",
    author: "Frederick Douglass",
    genre: "History",
    description:
      "A powerful autobiography of enslavement, literacy, resistance, and the claim to human freedom.",
    total_copies: 8,
    available_copies: 8,
    is_public_readable: true,
  },
  {
    id: "fallback-incidents-in-the-life-of-a-slave-girl",
    title: "Incidents in the Life of a Slave Girl",
    author: "Harriet Jacobs",
    genre: "History",
    description:
      "A vital slave narrative centered on motherhood, survival, concealment, and the violence of ownership.",
    total_copies: 8,
    available_copies: 8,
    is_public_readable: true,
  },
  {
    id: "fallback-the-importance-of-being-earnest",
    title: "The Importance of Being Earnest",
    author: "Oscar Wilde",
    genre: "Drama",
    description:
      "A sparkling comedy of names, manners, masks, and social absurdity sharpened into perfect farce.",
    total_copies: 7,
    available_copies: 7,
    is_public_readable: true,
  },
  {
    id: "fallback-grimms-fairy-tales",
    title: "Grimms' Fairy Tales",
    author: "Jacob Grimm and Wilhelm Grimm",
    genre: "Fairy Tales",
    description:
      "A classic collection of enchanted bargains, forest trials, transformations, danger, and folk justice.",
    total_copies: 9,
    available_copies: 9,
    is_public_readable: true,
  },
  {
    id: "fallback-andersens-fairy-tales",
    title: "Andersen's Fairy Tales",
    author: "Hans Christian Andersen",
    genre: "Fairy Tales",
    description:
      "Tender and strange literary fairy tales about longing, beauty, sacrifice, and difficult wonder.",
    total_copies: 9,
    available_copies: 9,
    is_public_readable: true,
  },
];

export const fallbackBooks: Book[] = [
  ...publicDomainShelfBooks.map(createFallbackBook),
  createFallbackBook({
    id: "fallback-the-alchemists-codex",
    title: "The Alchemist's Codex",
    author: "Iris Vale",
    genre: "Rare Archives",
    description:
      "A restored mystical manuscript that blends alchemy, astronomy, and symbolic diagrams from a lost monastery collection.",
    total_copies: 3,
    is_public_readable: true,
    reading_content: [
      "The codex opens with a page of patient instructions: do not begin with the metals, begin with the sky. In Iris Vale's archive, every recipe is paired with a star chart, as if transformation is less a trick of chemistry and more a discipline of attention.",
      "A second folio records the labor of unnamed caretakers who copied the text through winters, wars, and monastery fires. Their notes are quiet but revealing, proving the book was used beneath an open roof as much as inside a library.",
      "Near the center, the codex becomes practical. It teaches how to observe color, heat, and timing without surrendering to superstition, framing the manuscript as a bridge between medieval craft and scientific method.",
      "The closing passage returns to the night sky and suggests that all study is a form of alignment: the hand with the page, the page with the lamp, the lamp with the patient orbit of the stars.",
    ],
  }),
  createFallbackBook({
    id: "fallback-vellum-of-vanished-courts",
    title: "Vellum of Vanished Courts",
    author: "Cassian Moore",
    genre: "Rare Archives",
    description:
      "Court records, private petitions, and marginal notes revealing how forgotten kingdoms negotiated power in whispers.",
    total_copies: 2,
    available_copies: 1,
  }),
  createFallbackBook({
    id: "fallback-atlas-of-broken-seals",
    title: "Atlas of Broken Seals",
    author: "Naomi Quill",
    genre: "Rare Archives",
    description:
      "A collector's survey of sealed correspondences, coded stamps, and the rituals of trust in imperial archives.",
    total_copies: 3,
  }),
  createFallbackBook({
    id: "fallback-quietude-of-mind",
    title: "Quietude of Mind",
    author: "Anika Sen",
    genre: "Philosophy",
    description:
      "Meditative traditions, inner discipline, and consciousness studies brought into dialogue with modern cognitive science.",
    is_public_readable: true,
    reading_content: [
      "Anika Sen begins with a simple observation: the mind rarely suffers from a lack of information. It suffers from scattered attention, and quietude is framed not as forced silence but as an interior skill.",
      "The book moves between contemplative traditions and cognitive science without turning either into decoration. Breathing exercises sit beside research on focus, and restraint sits beside habit loops.",
      "Sen describes discipline as a compassionate architecture. Boundaries are not punishments; they are rooms where thought can finally hear itself and where grief can be carried without defining the whole horizon.",
      "By the end, quietude becomes less a destination than a trustworthy companion. Peace is not promised as perfection, but as a practice available even when the world stays noisy.",
    ],
  }),
  createFallbackBook({
    id: "fallback-stoic-lamps-in-the-dust",
    title: "Stoic Lamps in the Dust",
    author: "Helena Ward",
    genre: "Philosophy",
    description:
      "Essays on endurance, grace, and moral clarity written for readers who need steadiness more than slogans.",
    total_copies: 5,
  }),
  createFallbackBook({
    id: "fallback-ethics-of-the-threshold",
    title: "Ethics of the Threshold",
    author: "Jonas Mire",
    genre: "Philosophy",
    description:
      "On choice, responsibility, and what it means to act well when certainty never fully arrives.",
    total_copies: 4,
  }),
  createFallbackBook({
    id: "fallback-letters-on-inner-freedom",
    title: "Letters on Inner Freedom",
    author: "Daria Volkov",
    genre: "Philosophy",
    description:
      "Reflective letters on resilience, personal discipline, and the quiet dignity of deliberate living.",
    total_copies: 6,
    available_copies: 5,
  }),
  createFallbackBook({
    id: "fallback-archive-letters-from-the-steppe",
    title: "Archive Letters from the Steppe",
    author: "Mara Ellison",
    genre: "History",
    description:
      "A free-reading archival journey through family letters, trade routes, and memory carried across the grasslands.",
    total_copies: 6,
    available_copies: 6,
    is_public_readable: true,
    reading_content: [
      "The letters begin with weather, wind direction, horse fatigue, and the shape of clouds above the river crossings. Only gradually do they reveal their second purpose: preserving a moving world before distance flattens it into a single map.",
      "A merchant writes home about felt, salt, and rumor. A daughter records songs used to remember safe wells. A scribe notes how names change from camp to camp while affection survives every translation.",
      "As the archive deepens, the steppe stops feeling empty. Every campfire becomes a library and every exchange of directions becomes an exchange of ethics about how to host, warn, and remember.",
      "The final pages suggest that movement itself can be a form of scholarship. These letters ask to be read with the same respect usually reserved for capitals, empires, and stone.",
    ],
  }),
  createFallbackBook({
    id: "fallback-river-empires-and-salt",
    title: "River Empires and Salt",
    author: "Talia Brooks",
    genre: "History",
    description:
      "A sweeping trade history of caravans, ports, and the fragile agreements that built entire regions.",
    total_copies: 5,
  }),
  createFallbackBook({
    id: "fallback-midnight-chronicles-of-karakorum",
    title: "Midnight Chronicles of Karakorum",
    author: "Batsaikhan Erdene",
    genre: "History",
    description:
      "Fragments of political intrigue, diplomacy, and urban life reconstructed from a legendary Silk Road capital.",
    language: "mn",
    total_copies: 4,
    available_copies: 3,
  }),
  createFallbackBook({
    id: "fallback-kinship-beyond-borders",
    title: "Kinship Beyond Borders",
    author: "Lena Harrow",
    genre: "Anthropology",
    description:
      "Field notes on migration, belonging, and how communities preserve meaning across languages and generations.",
    total_copies: 6,
  }),
  createFallbackBook({
    id: "fallback-rituals-of-the-open-steppe",
    title: "Rituals of the Open Steppe",
    author: "Saruul Tseren",
    genre: "Anthropology",
    description:
      "An intimate study of seasonal rituals, oral memory, and hospitality practices that shape nomadic identity.",
    language: "mn",
    total_copies: 5,
    available_copies: 4,
  }),
  createFallbackBook({
    id: "fallback-maps-of-human-memory",
    title: "Maps of Human Memory",
    author: "Elias Monroe",
    genre: "Anthropology",
    description:
      "How storytelling, ritual objects, and collective mourning turn memory into shared social architecture.",
    total_copies: 4,
  }),
  createFallbackBook({
    id: "fallback-quantum-notes-for-curious-minds",
    title: "Quantum Notes for Curious Minds",
    author: "Leah Moritz",
    genre: "Quantum Physics",
    description:
      "Short, lucid chapters that turn difficult quantum ideas into readable thought experiments and everyday wonder.",
    total_copies: 7,
    available_copies: 7,
    is_public_readable: true,
    reading_content: [
      "Leah Moritz opens with a promise she keeps: no theatrics, no false certainty, and no condescension. Quantum theory is introduced as careful discovery rather than magic wearing science's costume.",
      "A page on probability is followed by a story about two musicians improvising from opposite rooms. The metaphor never replaces the idea, but it helps the reader feel why correlation can be stranger than distance.",
      "The shortest chapters are often the strongest. One explains measurement by talking about questions that change a room the moment they are asked, while another traces how elegance earns trust only after experiment answers back.",
      "By the final section, the reader is not expected to master the field. They are invited to become a better witness to reality's subtler rules.",
    ],
  }),
  createFallbackBook({
    id: "fallback-beyond-the-event-horizon",
    title: "Beyond the Event Horizon",
    author: "Marcus Thorne",
    genre: "Quantum Physics",
    description:
      "A cinematic exploration of black holes, paradoxes, and the edges of modern cosmology.",
    total_copies: 4,
  }),
  createFallbackBook({
    id: "fallback-entangled-midnights",
    title: "Entangled Midnights",
    author: "Rhea Sol",
    genre: "Quantum Physics",
    description:
      "A poetic but rigorous guide to uncertainty, entanglement, and the beauty of incomplete knowledge.",
    total_copies: 5,
  }),
  createFallbackBook({
    id: "fallback-measurement-and-mystery",
    title: "Measurement and Mystery",
    author: "Olivier Kane",
    genre: "Quantum Physics",
    description:
      "Explains why observation matters, where intuition breaks, and how experiments keep physics honest.",
    total_copies: 4,
    available_copies: 2,
  }),
  createFallbackBook({
    id: "fallback-sky-bridges-of-orion",
    title: "Sky Bridges of Orion",
    author: "Mina Kestrel",
    genre: "Cosmology",
    description:
      "A vivid tour of galaxies, stellar nurseries, and the large-scale structures that lace the universe together.",
    total_copies: 5,
    is_public_readable: true,
    reading_content: [
      "Mina Kestrel writes cosmology like a cartographer of awe. Distances are not used to diminish the reader, but to teach scale patiently, one orbit and one nebula at a time.",
      "The book keeps returning to bridges: between gravity and time, between starlight and memory, between what telescopes receive and what human language can almost hold.",
      "Rather than treating the universe as abstract emptiness, Kestrel makes structure visible. Voids, clusters, and spiral arms feel like parts of a conversation rather than cold diagrams.",
      "Its final chapters leave the reader with a steadier wonder: not shock at how large the cosmos is, but gratitude that it can be studied at all.",
    ],
  }),
  createFallbackBook({
    id: "fallback-theory-of-golden-dust",
    title: "Theory of Golden Dust",
    author: "Arman Lee",
    genre: "Cosmology",
    description:
      "On stardust, planet formation, and the improbable chemistry that turned cosmic debris into worlds.",
    total_copies: 4,
  }),
  createFallbackBook({
    id: "fallback-lanterns-at-the-edge-of-time",
    title: "Lanterns at the Edge of Time",
    author: "Priya Noor",
    genre: "Cosmology",
    description:
      "Dark matter, cosmic background light, and the methods scientists use to read an ancient universe.",
    total_copies: 6,
    available_copies: 4,
  }),
  createFallbackBook({
    id: "fallback-neural-architectures",
    title: "Neural Architectures",
    author: "Sarah Chen",
    genre: "AI",
    description:
      "A visual guide to learning systems, model design, and the philosophical questions beneath machine intelligence.",
    total_copies: 5,
  }),
  createFallbackBook({
    id: "fallback-neural-garden-handbook",
    title: "Neural Garden Handbook",
    author: "Owen Park",
    genre: "AI",
    description:
      "An approachable guide to machine learning told through the language of cultivation, pruning, feedback, and care.",
    total_copies: 8,
  }),
  createFallbackBook({
    id: "fallback-language-machines-at-dawn",
    title: "Language Machines at Dawn",
    author: "Farah Ibn Noor",
    genre: "AI",
    description:
      "From symbolic reasoning to modern language models, this book traces how machines learned to work with meaning.",
    total_copies: 6,
    available_copies: 5,
  }),
  createFallbackBook({
    id: "fallback-human-signal-human-noise",
    title: "Human Signal, Human Noise",
    author: "Devon Price",
    genre: "AI",
    description:
      "Bias, datasets, and the social responsibilities that arrive with every predictive system.",
    total_copies: 4,
  }),
  createFallbackBook({
    id: "fallback-orchard-of-borrowed-myths",
    title: "Orchard of Borrowed Myths",
    author: "Lin Yue",
    genre: "Mythology",
    description:
      "Comparative readings of origin myths, trickster tales, and the symbols cultures repeatedly return to.",
    total_copies: 5,
  }),
  createFallbackBook({
    id: "fallback-firekeepers-and-first-stars",
    title: "Firekeepers and First Stars",
    author: "Ariunbold Naran",
    genre: "Mythology",
    description:
      "A lyrical collection of sky legends, hearth rituals, and ancestral stories carried by oral tradition.",
    language: "mn",
    total_copies: 3,
    available_copies: 2,
  }),
  ...extendedFallbackBooks.map(createFallbackBook),
];
